### ISSUE TITLE
Make per-module link check tests faster

### ISSUE THREAD

**Issue by srid** [hercules-ci/flake.parts-website#216]
https://github.com/srid/haskell-flake/blob/8c295dd7d841dd904aafe0bba16829ce28a41fbf/doc/test.sh#L3-L5

This is bringing in the whole suite of flake inputs from this repo, which are not strictly needed just to do link check on haskell-flake. Doing this would improve the CI time for haskell-flake.

**Comment by roberth** [comment]
It shouldn't have to be slow. Most of the time seems to be spent on busywork, checking the same thing or parsing over and over.
 - we could try https://github.com/linkchecker/linkchecker/pull/661
 - or perhaps switch to a different tool

> bringing in the whole suite of flake inputs

I don't want to block cross-module links on the site. Ideally we can keep checking those.

**Comment by roberth** [comment]
Tried with lychee, but it's not quite ready for offline operation yet. See https://github.com/hercules-ci/flake.parts-website/pull/626

**Comment by roberth** [comment]
Lychee was merged in #626 :tada:
